### ISSUE TITLE
Repository cannot be cloned under Windows

### ISSUE THREAD

**Issue by imagingbook** [nlct/texparser#1]
This repository cannot be cloned under Windows, even via ZIP file. Reason is (which I just learned with surprise) that Windows does not allow directories to be named "aux" or "AUX". This happens for the path "lib/aux". I had to rename the contained Java package to make things work.

--Wilhelm

**Comment by nlct** [comment]
Thank you for letting me know. I'll have to rename it. Perhaps `auxfile`? (My initial thought of `auxlib` adds a bit of redundancy in `lib/auxlib`.) This will mean that all applications that use the `aux` classes will need to be updated (but there's currently no guarantee of backward compatibility at the moment anyway, as it's still very experimental).

**Comment by nlct** [comment]
I've found the [Microsoft documentation](https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file) that lists the reserved names (including `aux`). The last version of `texparserlib` to use the `aux` directory is [v0.7b](https://github.com/nlct/texparser/releases/tag/v0.7b). For future versions, the directory will be called `auxfile`.
