### ISSUE TITLE
Example for parsing a math expression

### ISSUE THREAD

**Issue by axkr** [nlct/texparser#6]
I would like to test your parser for the implementation of a converter from a "TeX math" string to a math "expression tree" for improving the implementation of the Symja `ToExpression` function:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/ToExpression.md

Do you have an example how to parse a "TeX math" expression with texparser?

**Comment by nlct** [comment]
I'm sorry, TeX Parser is still experimental and liable to change so there currently aren't any examples.

**Comment by axkr** [comment]
Ok, thank you. 
Should I close this issue, or keep it open as a reminder?

**Comment by nlct** [comment]
I think it can probably be closed. Once the library is more stable I'll add documentation and examples.
